version: "3.9"  # optional since v1.27.0
services:
  matchmaking-service:
    image: cool-game/matchmacking-service
    build:
      context: .
      dockerfile: ./MatchmakingService/Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - redis
  matchmaking-worker:
    image: cool-game/matchmacking-worker
    build:
      context: .
      dockerfile: ./MatchmakingWorker/Dockerfile
    ports:
      - "8084:80"
    depends_on:
      - redis
      - kafka
  matchmaking-test-client:
    image: cool-game/matchmacking-test-client
    build:
      context: .
      dockerfile: ./MatchmakingTestClient/Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - matchmaking-service
      - matchmaking-worker
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  redis:
    image: redis