version: "3.9"  # optional since v1.27.0
services:
  matchmaking-service:
    image: cool-game/matchmacking-serice
    build:
      context: .
      dockerfile: ./MatchmakingService/Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - redis
  redis:
    image: redis
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - "MAX_MAP_COUNT=262144"